export const appConstants = {
    SET_PLAYER_PLAYING: 'SET_PLAYER_PLAYING',
    TOGGLE_IS_PLAY_CLICKED: 'TOGGLE_IS_PLAY_CLICKED',
    SET_FETCH_IMAGE_LOADING: 'SET_FETCH_IMAGE_LOADING',
    SET_IMAGES: 'SET_IMAGES',
    SET_IMAGE_FETCH_ERROR: 'SET_IMAGE_FETCH_ERROR',
    ADD_PLAYER_PERFORMANCE: 'ADD_PLAYER_PERFORMANCE',
    SET_SCORE: 'SET_SCORE',
}
